// code.py -> {codePy, fastPy, srcPy}. turbo-web.md section 6.5.
//
// Never rewrites anything on the board; app.js shows this output before a
// single byte is written.
//
// Two forms of the module come out of here:
//   fastPy  @micropython.viper   what mpy-cross compiles
//   srcPy   @turbo.viper         what lands in /src, so the source fallback
//                                still runs on stock firmware (the CLI layout)

import { findFunctions } from "./analyze.js";

function params(header) {
  const open = header.indexOf("(");
  const close = header.lastIndexOf(")");
  if (open < 0 || close < open) return [];
  return header.slice(open + 1, close).split(",")
    .map((x) => x.split(/[:=]/)[0].trim()).filter(Boolean);
}

// Names the harness may call besides the lifted functions themselves.
const SAFE = new Set(["range", "len", "int", "abs", "min", "max", "sum", "bool",
                      "ord", "chr", "bytearray", "bytes", "array", "memoryview",
                      "list", "tuple", "enumerate", "zip", "round", "divmod"]);

export const MODULE = "fast";

// Bench harness appended to both forms. Calls each lifted function with
// arguments synthesized from its annotations, so the same work is timed from
// source and from the compiled module.
const BENCH_REPS = 120;

function benchArgs(header) {
  const open = header.indexOf("(");
  const close = header.lastIndexOf(")");
  const inner = header.slice(open + 1, close).trim();
  if (!inner) return [];
  return inner.split(",").map((p) => {
    const ann = (p.split(":")[1] || "").split("=")[0].trim();
    if (/^ptr(8|16|32)$/.test(ann)) return "_buf";
    return "64";
  });
}

// A driver already in the file beats a synthesized one: it calls the hot
// function with the arguments the program actually uses, so the measured
// ratio reflects real work rather than whatever the annotations allow.
// Eligible: top level, no parameters, and every call it makes is either a
// lifted function or a builtin, so it is self-contained inside the module.
export function findDriver(text, names) {
  for (const fn of findFunctions(text)) {
    if (names.includes(fn.name)) continue;
    if (params(fn.header).length) continue;
    const calls = (fn.body.join("\n").match(/([A-Za-z_][\w.]*)\s*\(/g) || [])
      .map((c) => c.replace(/\s*\($/, ""));
    if (calls.some((c) => c.includes("."))) continue;
    if (!calls.some((c) => names.includes(c))) continue;
    if (!calls.every((c) => names.includes(c) || SAFE.has(c))) continue;
    return fn;
  }
  return null;
}

function benchFor(fns, driver) {
  if (driver) {
    return [
      "",
      "",
      driver.text,
      "",
      "",
      "def _turbo_bench():",
      `    # the file's own ${driver.name}(), so the measurement is real work`,
      `    return ${driver.name}()`,
      "",
    ].join("\n");
  }
  const calls = fns.map((f) => `        ${f.name}(${benchArgs(f.header).join(", ")})`);
  return [
    "",
    "",
    "def _turbo_bench():",
    "    # generated by the turbo page: the same calls, timed either way",
    "    _buf = bytearray(256)",
    `    for _ in range(${BENCH_REPS}):`,
    ...calls,
    "    return _buf[0]",
    "",
  ].join("\n");
}

// Insert after the last top-level import that precedes the first statement.
function insertPoint(lines) {
  let last = -1;
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i];
    if (/^\s*#/.test(l) || !l.trim()) continue;
    if (/^(import|from)\s/.test(l)) { last = i; continue; }
    if (/^def\s|^class\s|^@/.test(l)) break;
    break;
  }
  return last + 1;
}

/**
 * @param {string} text     the user's code.py
 * @param {string[]} names  ticked function names
 * @returns {{codePy, fastPy, srcPy, moduleName, lineMap, lifted}}
 *   lineMap maps a 1-based line in fastPy back to the user's numbering.
 */
export function split(text, names) {
  const lines = text.split(/\r?\n/);
  const fns = findFunctions(text).filter((f) => names.includes(f.name));
  if (!fns.length) throw new Error("nothing ticked");

  // ---- the module ---------------------------------------------------
  const fastLines = ["# generated by the turbo page. compiled with mpy-cross.", ""];
  const srcLines = ["# generated by the turbo page. source fallback.",
                    "from turbo import turbo", ""];
  const lineMap = {};                       // fastPy line -> original line

  for (const fn of fns) {
    const body = fn.text.split("\n").filter((l) => !/^@/.test(l.trim()));
    fastLines.push("@micropython.viper");
    srcLines.push("@turbo.viper");
    for (let i = 0; i < body.length; i++) {
      lineMap[fastLines.length + 1] = fn.defLine + i;
      fastLines.push(body[i]);
      srcLines.push(body[i]);
    }
    fastLines.push("", "");
    srcLines.push("", "");
  }
  const driver = findDriver(text, names);
  const bench = benchFor(fns, driver);
  const fastPy = fastLines.join("\n").replace(/\n+$/, "\n") + bench;
  const srcPy = srcLines.join("\n").replace(/\n+$/, "\n") + bench;

  // ---- the edited code.py -------------------------------------------
  const cut = new Set();
  for (const fn of fns) {
    for (let i = fn.line - 1; i <= fn.endLine - 1; i++) cut.add(i);
  }
  const kept = lines.filter((_, i) => !cut.has(i));
  const at = insertPoint(kept);
  kept.splice(at, 0,
    "import turbo",
    `from ${MODULE} import ${fns.map((f) => f.name).join(", ")}`);
  const codePy = kept.join("\n").replace(/\n{3,}/g, "\n\n\n");

  return {
    codePy, fastPy, srcPy, moduleName: MODULE, lineMap,
    driver: driver ? driver.name : null,
    lifted: fns.map((f) => ({ name: f.name, line: f.line, endLine: f.endLine, count: f.endLine - f.line + 1 })),
  };
}

// The left column of "What changes": the original with the lifted defs struck
// out and the two new imports marked added. Bodies elide to one line.
export function diffView(text, names) {
  const lines = text.split(/\r?\n/);
  const fns = findFunctions(text).filter((f) => names.includes(f.name));
  const out = [];
  const at = insertPoint(lines.filter((_, i) =>
    !fns.some((f) => i >= f.line - 1 && i <= f.endLine - 1)));

  let shown = 0;
  for (let i = 0; i < lines.length; i++) {
    const fn = fns.find((f) => i === f.line - 1);
    if (fn) {
      out.push({ kind: "del", text: lines[fn.defLine - 1] });
      const n = fn.endLine - fn.defLine;
      if (n > 0) out.push({ kind: "del", text: `    ... ${n} lines ...` });
      i = fn.endLine - 1;
      continue;
    }
    if (fns.some((f) => i > f.line - 1 && i <= f.endLine - 1)) continue;
    if (shown === at) {
      out.push({ kind: "add", text: "import turbo" });
      out.push({ kind: "add", text: `from ${MODULE} import ${fns.map((f) => f.name).join(", ")}` });
    }
    out.push({ kind: "same", text: lines[i] });
    shown++;
  }
  if (shown === at) {
    out.push({ kind: "add", text: "import turbo" });
    out.push({ kind: "add", text: `from ${MODULE} import ${fns.map((f) => f.name).join(", ")}` });
  }
  return out;
}

// Compiler line N in fastPy -> the user's line number.
export function mapLine(lineMap, n) {
  if (!n) return null;
  return lineMap[n] || null;
}
