# generated by the turbo page. compiled with mpy-cross.

@micropython.viper
def mandel_row(out: ptr8, width: int, dx: int, cy: int, max_iter: int):
    # fixed point, 12 fractional bits, integers only so viper can take it
    for px in range(width):
        cx = px * dx - (2 << 12)
        x = 0
        y = 0
        i = 0
        while i < max_iter:
            x2 = (x * x) >> 12
            y2 = (y * y) >> 12
            if x2 + y2 > (4 << 12):
                break
            y = ((x * y) >> 11) + cy
            x = x2 - y2 + cx
            i += 1
        out[px] = i


def _turbo_bench():
    # generated by the turbo page: the same calls, timed either way
    _buf = bytearray(256)
    for _ in range(120):
        mandel_row(_buf, 64, 64, 64, 64)
    return _buf[0]
